### ISSUE TITLE
Occasional fails with circleci

### ISSUE THREAD

**Issue by Cadair** [nbedos/cistern#24] opened 2020-01-29 20:05 UTC
I have seen errors along these lines a couple of times now:

> cistern: Provider circleci-0: monitorPipeline failed with parsing time "" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "2006" (https://circleci.com/gh/sunpy/sunpy/36079?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

It seems to happen on a newly pushed branch, maybe force pushes? Let me know if there is  anything I can do to get more details when it happens.

**Comment by Cadair** [comment] 2020-01-29 20:05
yeah, after a short while it goes away on the same branch.

**Comment by nbedos** [comment] 2020-01-29 20:23
Thanks for reporting this. It seems that the Circle CI API sends `cistern` a build without a creation date and `cistern` fails because this date is mandatory. I think I have enough information to fix this, I'll let you know when I have a solution.

**Comment by Cadair** [comment] 2020-01-29 20:38
my best guess at the moment is that it's because the build is still pending, but I am not 100% sure.

**Comment by nbedos** [comment] 2020-01-30 10:14
Yes, that's probably it. I changed `cistern` so that the date causing the crash may now be `null`. The fix is on this branch: https://github.com/nbedos/cistern/tree/bugfix/optional_creation_date

If you're able to reproduce the crash fairly easily I can leave the fix on this branch for now for you to test, if not I can merge it in `master`. I'm fairly confident in the changes I made so I'm OK with merging them without further testing.

**Comment by Cadair** [comment] 2020-01-30 13:55
My initial testing indicates this is working, I will let you know how it goes over a few more branches etc.

**Comment by Cadair** [comment] 2020-01-30 15:02
I tested this out on the azure branch (which seemed to also have these fixes in?) seems to work well.

**Comment by nbedos** [comment] 2020-02-05 14:37
Thanks for testing this. I just merged my changes in `master`.

**Closed by nbedos** 2020-02-05 14:37 UTC
Labels: CircleCI, bug
