### ISSUE TITLE
Support for private gitlab instance

### ISSUE THREAD

**Issue by gmembre-zenika** [nbedos/cistern#16] opened 2020-01-02 13:20 UTC
Hi, 

Thanks for your work ! 💪 

I have a private gitlab and cistern is not able to retrieve the pipeline status. 
The remote of my repo is : `https://gitlab.xxx.yy/a/long/path/my-repos.git`.

I have added some logs in the function `Commit()` of `providers/gitlab.go`, the url requested is : `https://gitlab.xxx.yy/api/v4/projects/a/long/repository/commits/abcedf`
where as, it should be `https://gitlab.xxx.yy/api/v4/projects/<id>/repository/commits/abcdef`.

The `<id>` of the project can be retrieved by calling `https://gitlab.xxx.yy/api/v4/projects?search=my-repos` (<= note that there is no namespace) and extract the id from the json response.

I can help to test and debug. I just don't know where to put this new functionnality. 

What do you think ?

**Comment by nbedos** [comment] 2020-01-02 19:28
You're welcome and thank you for reporting this.

Quoting from the [documentation](https://docs.gitlab.com/ee/api/commits.html), it is valid to call `GET /projects/:id/repository/commits` where  `:id` is "The ID or URL-encoded path of the project owned by the authenticated user".

So using the path of the project should work, as long as it's correctly encoded. I noticed that URL encoding is done both in `cistern` and in `go-gitlab` which doesn't make any sense and probably leads to the issue you're experiencing. I made a few changes on the following branch that fixes this: https://github.com/nbedos/cistern/tree/bugfix/gitlab_url_encoding 

Could you please let me know if they fix this issue?

Thanks

**Comment by gmembre-zenika** [comment] 2020-01-03 09:49
I tried you fix and it doesn't work.

I tested manually different call to `GET /projects/:id/repository/commits` with `curl` and the only one which works is with the `:id` with the numeric project id.
I'm using gitlab 12.5.1.

**Comment by nbedos** [comment] 2020-01-03 13:45
Alright, I think now I understand. The path of the repository is truncated by `cistern` because I assumed all repository paths would follow the format `owner/repository`, which is wrong. The example you gave in your first post shows this but somehow I missed it.

I made a few changes on the same branch as yesterday: https://github.com/nbedos/cistern/tree/bugfix/gitlab_url_encoding

Now `cistern` is able to list the pipelines of random public GitLab repositories with arbitrary long namespaces. For example it works with https://gitlab.com/gitmate/open-source/IGitt and https://gitlab.com/gitlab-com/gl-security/gl-redteam/token-hunter
Does it work for yours too?

As for relying on the numeric ID of the repository, I'd rather avoid making an extra API call to translate the path of the repository (which is a valid repository ID) into another repository ID. As far as I understand you just have to properly escape the repository path. For example getting the project resource of the API for https://gitlab.com/gitlab-com/gl-security/gl-redteam/token-hunter is achieved by running:
```
curl  https://gitlab.com/api/v4/projects/gitlab-com%2Fgl-security%2Fgl-redteam%2Ftoken-hunter
```

**Comment by gmembre-zenika** [comment] 2020-01-03 14:39
unfortunately, gitlab returns a 404 which this new version while calling the `commit` API.

**Comment by gmembre-zenika** [comment] 2020-01-03 15:18
I would like to try with the id of my project hardcoded. Where can I put it please ?

In `parsePipelineURL()` of `providers/gitlab.go` ?
eg : 
```
return "1234", id, nil
```

**Comment by nbedos** [comment] 2020-01-03 15:25
I don't get why it works with public instances but not with yours.

You suggested using the numeric ID so I take it you made API calls using `curl` or another method and got a response for that specific repository? So you have the proper permissions to access the repository via the API.

Are there characters outside the range `[a-zA-Z]` in the path of the repository ? Or in the name of the tag or branch returned by `git rev-parse --abbrev-ref HEAD`.



> I would like to try with the id of my project hardcoded. Where can I put it please ?
> 
> In `parsePipelineURL()` of `providers/gitlab.go` ?
> eg :
> 
> ```
> return "1234", id, nil
> ```

Yes, you need to replace `slug` by the id of your repository for both `parseRepositoryURL` and `parsePipelineURL`

**Comment by nbedos** [comment] 2020-01-10 17:12
Although the changes I've made thanks to this bug report do not resolve this issue I've merged them into master because they solve other bugs.

I'm unable to reproduce the initial bug without further information and so I will be closing this issue. Anyone with additional information on this problem that could help reproduce it is welcome to comment here or to open another issue.

**Closed by nbedos** 2020-01-10 17:12 UTC
Labels: bug
